package main

import (
	"bufio"
	"encoding/json"
	"log"
	"net"
	"sync"

	"github.com/Shopify/sarama"
)

// Node is used by json.Unmarshal() to check JSON generated by the instrument.
type Node struct {
	Fn       uint64 `json:"fn,omitempty"`
	Cs       uint64 `json:"cs,omitempty"`
	Ncalls   uint   `json:"ncalls,omitempty"`
	Nsamples uint   `json:"nsamples,omitempty"`
	//Callees  []Node `json:"callees,omitempty"`
	Callees  []Node `json:"callees"`
	CheckSum string `json:"checksum,omitempty"`
}

func relay(server net.Listener, sum string, wg *sync.WaitGroup) {
	defer wg.Done()

	conn, err := server.Accept()
	check(err)

	producer, err := connect()
	check(err)
	defer producer.Close()

	line := bufio.NewScanner(conn)
	for line.Scan() {
		var n Node
		err := json.Unmarshal(line.Bytes(), &n)
		if err != nil {
			panic(err)
		}

		log.Println("wrapper: got", len(line.Bytes()), "B of valid JSON")

		n.CheckSum = sum
		b, err := json.Marshal(n)
		check(err)

		log.Println(string(b))

		p, o, err := producer.SendMessage(&sarama.ProducerMessage{
			Topic: "616t-default",
			Value: sarama.ByteEncoder(b),
		})
		check(err)
		log.Printf("wrapper: partition %v, offset %v, %v\n", p, o, err)
	}
}
